---
title: '`r params$title`'
author: '`r params$author`'
date: '`r Sys.Date()`'
execute: 
  echo: false
  message: false
  warning: false
params:
  datafile: NULL
  title: "default title"
  year: 2022
  registry: "河南省"
  author: "河南省肿瘤登记处"
format:
  html: default
---

```{r}
#| label: setup
pkgs <- c("canregtools", "dplyr", "tidyr", "flextable")
for (pkg in pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
}
mess <- lapply(pkgs, library, character.only = TRUE)
data("quality")
std <- quality |> filter(year == 2017)
```

```{r}
data <- readRDS(params$datafile)
```

```{r}
df <- create_quality(data, year) |>
  add_labels(vars = "areacode") |> 
  filter(year == params$year) |>
  select(-cancer, -sex, -year) |>
  mutate(area = paste0(substr(areacode, 1, 4), "00"),
         area_cn = tidy_var(area, var_name = "areacode", lang = "cn")
         ) |>
  group_split(area)
```

```{r}
#| output: asis
for (i in seq_along(df)) {
  dat <- df[[i]]
  city <- dat |> 
    pull(area_cn) |> 
    unique()

  res <- knitr::knit_child(
    input = here::here("_qua.qmd"), 
    envir = environment(),
    quiet = TRUE)
  cat(res, sep = '\n')
}
```


