---
title: '`r paste0(params$year, params$registry, params$title)`'
subtitle: '`r paste("Annual Cancer Registry Report, ", params$year)`' 
author: "`r params$author`"
date: '`r Sys.Date()`'
footer: '`r paste0(params$year, params$title)`'
header: "Powered by canregtools, made by Qiong Chen"
cover-note: "本报告基于初步数据编制，仅用于内部质量控制目的，未经授权不得发布或用于公众传播。"
lang: ZH
params:
  datafile: NULL
  title: "肿瘤登记报告"
  author: "河南省癌症中心发布"
  year: NULL
  registry: "宜阳县"
execute: 
  echo: false
  message: false
  warning: false
format:
  typst:
    toc: true
---

```{r}
#| label: setup
r_packages <- c("canregtools", "flextable", "dplyr", "epoxy", "tidyr")

for (pkg in r_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
}

library(canregtools)
library(flextable)
library(dplyr)
library(epoxy)
library(tidyr)
font_report <- "Songti SC"
colors <- c("#0072B2", "#E69F00", "#009E73")
set_flextable_defaults(
  font.family = font_report,
  font.size = 11,
  text.align = "center",
  align = "center",
  border.color = "black",
  border.width = 0.3,
  line_spacing = 1.5,
  table_align = "center"
  )

epoxy_transform_set(
  .per = function(x) paste0(x, "%"),
  .percent = scales::label_percent(accuracy = 0.01),
  .and = function(x) glue::glue_collapse(x, sep = "，", last = "和"),
  .rate = function(x) paste0(x, "/10万")
)

theme_report <- function(
    ft,
    blank_i = NULL,
    blank_j = NULL
    ) {
  border_thick <- fp_border_default(width = 1)
  border_thin  <- fp_border_default(width = 0.5)

  n_head <- nrow_part(ft, "header")
  n_body <- nrow_part(ft, "body")
  ft <- border_remove(ft)
  for (i in 1:n_head) {
    top_border <- if (i == 1) border_thick else border_thin
    ft <- border(
      ft,
      i = i,
      border.top = top_border,
      part = "header")
  }

  ft <- border(
    ft,
    i = n_head,
    border.bottom = border_thin,
    part = "header")
    
  if (!is.null(blank_i)) {
    ft <- border(
      ft,
      i = blank_i,
      j = blank_j,
      border.top = border_none,
      part = "header")
  }

  ft <- border(
    ft,
    i = n_body,
    border.bottom = border_thick,
    part = "body")
  return(ft)
}

```



```{r}
year <- params$year
data <- readRDS(params$datafile)
if (is.null(year)){
  pop <- get_pop(data)
  year <- unique(purrr::pluck(pop, "year"))
  
}
areacode <- data$areacode
name <- tidy_var(areacode, var_name = "areacode", lang = "cn")
fbsw <- count_canreg(data)
```

## 登记处覆盖人口情况

```{r}
pop <- fbsw$pop
male <- sum(pop$rks[1:19])
female <- sum(pop$rks[20:36])
```

```{epoxy}
{name}肿瘤登记处覆盖人口总数为{.comma male+female}，其中男性人口数为{.comma male}，占全部人口数的{.percent male/(male+female)}；女性人口数为{.comma female}，占全部人口数的{.percent female/(male+female)}，男女人口数性别比为{.percent male/female} (见 @fig-pyramid-plot)。
```


```{r}
#| label: fig-pyramid-plot
#| fig-cap: !expr 'paste0(year, "年", name, "户籍人口金字塔")'
#| fig-height: 5
#| fig-width: 7
par(family = font_report)
draw_pyramid(fbsw$pop,
             x = agegrp,
             y = rks,
             group = sex,
             show_value = FALSE,
             csize = 0.7,
             grid = c(1, 1),
             cgap = 0.3,
             gl = NULL,
             labs = c("男性", "年龄", "女性")
             )
```

{{< pagebreak >}}

## `r year`年数据质量情况

```{r}
qua <- create_quality(fbsw, decimal = 2, year, sex, cancer) |>
  cr_filter(drop = "others", !cancer == 61, sex == 0) |> 
  add_labels(vars = c("cancer"), label_type = "abbr") |>
  select(cancer, cancer_cn, mi, mv, ub, sub, dco, mvs)
qua1 <- qua |> filter(!cancer == 60)
qua_mi <- qua1 |> arrange(desc(mi))
qua_mv <- qua1 |> arrange(desc(mv))
qua_sub <- qua1 |> arrange(desc(sub))
```

```{r}
#| output: asis
epoxy("@tbl-quality 显示了{year}年{name}肿瘤登记处质量控制指标情况，死亡发病比(M:I)为{mi}, 病理学诊断比例(MV)为 {.percent mv/100}，只有死亡医学证明书的病例所占比例(DCO)为{.percent dco/100}，发病亚部位不详的病例所占比例为{.percent sub/100}。\n", .data = qua |> filter(cancer == 60))

epoxy("死亡发病比(M:I)是反映肿瘤患者预后的指标，M:I越小预后越好，反之，则越差，(1-M:I)可以近似估计5年生存率。从不同癌症发病部位来看，M:I 前5位的癌症部位为{.and cancer_cn[1:5]}，其值分别为{.and mi[1:5]}；M:I 最低的癌症部位为{.and tail(cancer_cn, 5)}，其值分别为{.and tail(mi, 5)}。\n", .data = qua_mi)

epoxy("病理诊断比例(MV%)是评价数据有效性的重要指标，其值越高数据有效行越高，反之，则有效性越低；但是MV%过高也可反映数据存在完整性不足的问题。MV% 最高的癌症部位为{.and head(cancer_cn, 5)}，其值分别为{.and .per head(mv, 5)}；
MV% 最低的癌症部位为{.and tail(cancer_cn, 5)}，其值分别为{.and .per tail(mv, 5)}。\n", .data = qua_mv)

epoxy("
亚部位不明比例(SUB%)是评价数据有效性的指标之一，SUB% 最高的癌症部位为{.and head(cancer_cn, 5)}，其值分别为{.and .per head(sub, 5)}；
SUB% 最低的癌症部位为{.and tail(cancer_cn, 5)}，其值分别为{.and .per tail(sub, 5)}。", .data = qua_sub)
```



```{r}
#| label: tbl-quality
#| tbl-cap: !expr 'paste0(year, "年", name,  "肿瘤登记质量控制指标")'
par(family = font_report)
qua |>
  select(-cancer) |>
  arrange(cancer_cn) |>
  flextable() |>
  set_header_labels(
    cancer_cn = "癌症部位", mi = "M:I", mv = "MV%", dco = "DCO%",
    ub = "UB%", sub = "SUB%", mvs = "MVs%"
    ) |>
  line_spacing(space = 2, part = "header") |>
  theme_report()
```

{{< pagebreak >}}

## 恶性肿瘤发病情况
### 总体发病情况

```{r}
asr <- create_asr(fbsw, year, sex, decimal = 2) |>
  add_labels(label_type = "abbr") |>
  arrange(sex)
no_cases <- asr |> pull(no_cases)
cr <- pull(asr, cr)
asrcn <- pull(asr, asr_cn2000)
```

```{epoxy}
{year}年，{name}共诊断{.bold no_cases[1]}例肿瘤病例，其中，男性{no_cases[2]}，女性{no_cases[3]}。总体发病率为{.rate cr[1]}，中标发病率为{.rate asrcn[1]}，呈现男性{ifelse(asrcn[2] > asrcn[3], "高于", "低于")}女性的特点（男性vs女性：{.rate asrcn[2]} *vs* {.rate asrcn[3]}）。（见 @tbl-inci-total）

```


```{r}
#| label: tbl-inci-total
#| tbl-cap: !expr 'paste0(year, "年", name, "总体恶性肿瘤发病情况")'
par(family = font_report)
asr |>
  select(sex_cn, no_cases, cr, asr_cn2000, asr_wld85, truncr_cn2000, cumur) |>
  flextable() |>
  set_header_labels(
    sex_cn = "性别", no_cases = "病例数", cr = "粗率\n(1/10万)",
    asr_cn2000 = "中标率\n(1/10万)", asr_wld85 = "世标率\n(1/10万)",
    truncr_cn2000 = "截缩率\n35-64岁\n(1/10万)", cumur = "累积率\n0-74岁\n(%)"
    ) |>
  width(width = 1) |>
  align(align = "center", part= "all") |> 
  theme_report()
```

### 前十位恶性肿瘤发病情况

```{r}
asr <- create_asr(data, year, sex, cancer, decimal = 2) |>
  cr_filter(drop = c("total","others")) |>
  add_labels(var = "cancer", label_type = "abbr") |>
  add_labels(var = "sex", label_type = "full") |>
  group_by(sex) |>
  arrange(sex, desc(cr)) |>
  mutate(id = row_number()) |>
  slice_head(n = 10) |>
  ungroup()
total <- asr |> filter(sex == 0)
male <- asr |> filter(sex == 1)
female <- asr |> filter(sex == 2)
```

```{r}
#| output: asis
epoxy("{year}年，{name}")
epoxy("发病率前十位的恶性肿瘤分别为{.and cancer_cn}，其发病数占全部恶性肿瘤的{.percent sum(prop)[1]/100}；", .data = total)
epoxy("男性前十位恶性肿瘤分别为{.and cancer_cn}，其发病数占全部男性恶性肿瘤发病数的{.percent sum(prop)/100}；", .data = male)
epoxy("女性前十位恶性肿瘤分别为{.and cancer_cn}，其发病数占全部女性恶性肿瘤发病数的{.percent sum(prop)[1]/100}。（见： @fig-top10-inci， @tbl-top10-inci）", .data = female)
```

```{r}
agerate <- create_age_rate(fbsw, year) |>
  mutate(agegrp = as.integer(as.character(
    factor(agegrp, labels = c(0, 1, seq(5, 85, 5))))))
lowage <- tail(agerate$agegrp[agerate$rate < 200], 1)
maxage <- agerate$agegrp[which.max(agerate$rate)]
```

### 恶性肿瘤年龄别发病率

```{epoxy}
{year}年, {name}恶性肿瘤年龄别发病率在{lowage}岁年龄组之前相对较低，低于200/10万，在{lowage}岁年龄组之后，年龄别发病率随着年龄的增加而升高，在{maxage}岁年龄组达到峰值，其值为{.rate round(max(agerate$rate), 2)} {ifelse(!maxage == 85, "，之后年龄别发病率逐渐降低。", "。")}
在55岁年龄组之前年别发病率呈现女性高于男性的特点，之后则呈现男性高于女性的特点。（见 @fig-agerate-total-inci）
```


```{r}
agerate <- create_age_rate(fbsw, year, sex) |>
  add_labels(label_type = "abbr") |>
  mutate(agegrp = as.integer(as.character(
    factor(agegrp, labels = c(0, 1, seq(5, 85, 5))))))
```

```{r}
#| label: fig-top10-inci
#| fig-cap: !expr 'paste0(year, "年", name, "前十位恶性肿瘤发病率")'
#| fig-height: 6
#| fig-width: 8
par(family = font_report)
asr |>
  cr_filter(!sex == 0) |>
  select(sex_cn, cancer_cn, cr, asr_cn2000, asr_wld85) |>
  pivot_longer(cols = c(cr, asr_cn2000, asr_wld85),
               names_to = "group", values_to = "rate") |>
draw_barchart(x = cancer_cn,
              y = rate,
              group = group,
              facet = sex_cn, gl = 10,
              legend_label = c("粗率", "世标率", "中标率"),
              legend_pos = c(0.5, 0.2), grid = c(1,1),
              cols = colors,
              space = 0.8)
```


```{r}
#| label: fig-agerate-total-inci
#| fig-cap: !expr 'paste0(year, "年", name, "恶性肿瘤年龄别发病率")'
#| fig-height: 6
#| fig-width: 8
par(family = font_report)
draw_linechart(agerate, x = agegrp, y = rate, group = sex_cn,
               x_axis = c(0, seq(5, 85, 5)),
               group_var = sex,
                line_type = "b", cols = colors,
               axis_title = c("年龄", "年龄别率"))
```

{{< pagebreak >}}



:::{.landscape}

```{r}
#| label: tbl-top10-inci
#| tbl-cap: !expr 'paste0(year, "年", name, "前十位恶性肿瘤发病情况")'
par(family = font_report)
asr |>
  select(id, sex_cn, cancer_cn, no_cases, cr, asr_cn2000, prop) |>
  pivot_wider(names_from = "sex_cn",
              values_from = c(cancer_cn, no_cases, cr, asr_cn2000, prop),
              names_vary = "slowest") |>
  flextable() |>
  set_header_labels(
    values = c("顺位",
               rep(c("部位", "病例数","粗率\n(1/10万)",
                     "中标率\n(1/10万)", "构成比\n(%)"), 3)
               )) |>
  add_header_row(
    values = c("顺位",
               "部位", rep("合计", 4),
               "部位", rep("男性", 4),
               "部位", rep("女性", 4))) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(align = "center", part = "all") |>
  height_all(height = 0.6) |>
  set_table_properties(width = 1, layout = "autofit") |>
  theme_report()
```

:::


### 不同部位恶性肿瘤年龄别发病率

```{r}
agerate <- create_age_rate(fbsw, year, sex, cancer) |>
  cr_filter(drop = "others") |> 
  filter(cancer %in% c(103:106, 110, 114, 115, 118, 122:125),
         !sex == 0) |>
  add_labels(label_type = "abbr") |>
  mutate(agegrp = as.integer(as.character(
    factor(agegrp, labels = c(0, 1, seq(5, 85, 5))))))
```

```{r}
#| label: fig-agerate-inci
#| fig-cap: !expr 'paste0(year, "年", name, "主要部位恶性肿瘤年龄别发病率")'
#| fig-width: 8
#| fig-height: 11
par(family = font_report)
draw_linechart(agerate, x = agegrp, y = rate, group = sex_cn,
               facet = cancer_cn,
               x_axis = c(0, seq(5, 85, 5)),
               grid = c(4, 3), group_var = sex, cols = colors,
               axis_title = c("年龄", "年龄别率"))
```

{{< pagebreak >}}

## 恶性肿瘤死亡情况
### 总体死亡情况

```{r}
asr <- create_asr(data, event = "sws", year, sex, decimal = 2) |>
  add_labels() |>
  arrange(sex)
no_cases <- pull(asr, no_cases)
cr <- pull(asr, cr)
asrcn <- pull(asr, asr_cn2000)
```

```{epoxy}
{year}年，{name}共{.bold no_cases[1]}例病例因癌症死亡，其中，男性{no_cases[2]}，女性{no_cases[3]}。总体死亡率为{.rate cr[1]}，中标死亡率为{.rate asrcn[1]}，呈现男性{ifelse(asrcn[2] > asrcn[3], "高于", "低于")}女性的特点（男性vs女性：{.rate asrcn[2]} *vs* {.rate asrcn[3]}）。（见 @tbl-mort-total）
```


```{r}
#| label: tbl-mort-total
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤总体死亡情况")'
par(family = font_report)
asr |>
  select(sex_cn, no_cases, cr, asr_cn2000,
         asr_wld85, truncr_cn2000, cumur) |>
  flextable() |>
  set_header_labels(
    sex_cn = "性别", no_cases = "病例数", cr = "粗率\n(1/10万)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)",
    truncr_cn2000 = "截缩率\n35-64岁\n(1/10万)",
    cumur = "累积率\n0-74岁\n(%)") |>
  align(j = c(1:7), align = "center", part = "all") |>
  width(width = 1) |> 
  theme_report()
```

### 前十位恶性肿瘤死亡情况

```{r}
asr <- create_asr(fbsw, event = "sws", year, sex, cancer, decimal = 2) |>
  cr_filter(drop = c("total", "others")) |> 
  add_labels(var = "cancer", label_type = "abbr") |>
  add_labels(var = "sex", label_type = "full") |>
  group_by(sex) |>
  arrange(sex, desc(cr)) |>
  mutate(id = row_number()) |>
  slice_head(n = 10) |>
  ungroup()
total <- asr |> filter(sex == 0)
male <- asr |> filter(sex == 1)
female <- asr |> filter(sex == 2)
```

```{r}
#| output: asis
epoxy("{year}年，{name}")
epoxy("恶性肿瘤死亡率的前十位分别为{.and cancer_cn}，其死亡数占全部恶性肿瘤的{.percent sum(prop)/100}；", .data = total)
epoxy("男性前十位恶性肿瘤分别为{.and cancer_cn}，其死亡数占全部男性恶性肿瘤的{.percent sum(prop)/100}；", .data = male)
epoxy("女性前十位恶性肿瘤分别为{.and cancer_cn}，其死亡数占全部女性恶性肿瘤的{.percent sum(prop)/100}。（见： @fig-top10-mort， @tbl-top10-mort）", .data = female)
```

```{r}
agerate <- create_age_rate(fbsw, event = "sws", year) |>
  mutate(agegrp = as.integer(as.character(
    factor(agegrp, labels = c(0, 1, seq(5, 85, 5))))))
lowage <- tail(agerate$agegrp[agerate$rate < 200], 1)
maxage <- agerate$agegrp[which.max(agerate$rate)]
```

### 恶性肿瘤年龄别死亡率

```{epoxy}
{year}年, {name}恶性肿瘤年龄别死亡率在{lowage}岁年龄组之前相对较低，低于150/10万，在{lowage}岁年龄组之后，年龄别死亡率随着年龄的增加而升高，在{maxage}岁年龄组达到峰值，其值为{.rate round(max(agerate$rate), 2)} {ifelse(!maxage == 85, "，之后年龄别发病率逐渐降低。", "。")} 不同年龄组的年别死亡率均呈现男性高于女性的特点。（见 @fig-agerate-total-mort）
```

```{r}
#| label: fig-top10-mort
#| fig-cap: !expr 'paste0(year, "年", name, "前十位恶性肿瘤死亡情况")'
#| fig-height: 6
#| fig-width: 8
par(family = font_report)
asr |>
  cr_filter(!sex == 0) |>
  select(sex_cn, cancer_cn, cr, asr_cn2000, asr_wld85) |>
  pivot_longer(cols = c(cr, asr_cn2000, asr_wld85),
               names_to = "group", values_to = "rate") |>
draw_barchart(x = cancer_cn,
              y = rate,
              group = group,
              facet = sex_cn, gl = 10, cols = colors,
              legend_label = c("粗率", "世标率", "中标率"),
              legend_pos = c(0.5, 0.2), grid = c(1,1),
              space = 0.8)
```

```{r}
agerate <- create_age_rate(fbsw, event = "sws", year, sex) |>
  add_labels(label_type = "full") |>
    mutate(agegrp = as.integer(as.character(
    factor(agegrp, labels = c(0, 1, seq(5, 85, 5))))))
```

```{r}
#| label: fig-agerate-total-mort
#| fig-cap: !expr 'paste0(year, "年", name, "恶性肿瘤年龄别死亡率")'
#| fig-height: 6
#| fig-width: 8
par(family = font_report)
draw_linechart(agerate, x = agegrp, y = rate, group = sex_cn,
              x_axis = c(0, seq(5, 85, 5)),
              group_var = sex_cn,
              line_type = "b", cols = colors,
              axis_title = c("年龄", "年龄别率"))
```

{{< pagebreak >}}

:::{.landscape}

```{r}
#| label: tbl-top10-mort
#| tbl-cap: !expr 'paste0(year, "年", name, "前十位恶性肿瘤死亡情况")'
par(family = font_report)
asr |>
  select(id, sex_cn, cancer_cn, no_cases, cr, asr_cn2000, prop) |>
  pivot_wider(names_from = "sex_cn",
              values_from = c(cancer_cn, no_cases, cr, asr_cn2000, prop),
              names_vary = "slowest") |>
  flextable() |>
  set_header_labels(
    values = c("顺位",
               rep(c("部位", "病例数","粗率\n(1/10万)",
                     "中标率\n(1/10万)", "构成比\n(%)"), 3)
               )) |>
  add_header_row(
    values = c("顺位",
               "部位", rep("合计", 4),
               "部位", rep("男性", 4),
               "部位", rep("女性", 4))) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(align = "center", part = "all") |>
  theme_report()
```

:::


### 不同部位恶性肿瘤年龄别死亡率

```{r}
agerate <- create_age_rate(data,
                           event = "sws", year, sex, cancer) |>
  cr_filter(cancer %in% c(103:106, 110, 114, 115, 118, 122:125),
            !sex == 0) |>
  add_labels(label_type = "abbr") |>
  mutate(agegrp = as.integer(as.character(
    factor(agegrp, labels = c(0, 1, seq(5, 85, 5))))))
```

```{r}
#| label: fig-agerate-mort
#| fig-cap: !expr 'paste0(year, "年", name, "主要部位恶性肿瘤年龄别死亡率")'
#| fig-align: "center"
#| fig-width: 8
#| fig-height: 11
par(family = font_report)
draw_linechart(agerate, x = agegrp, y = rate, group = sex_cn,
               facet = cancer_cn, grid = c(4, 3), 
               x_axis = c(0, seq(5, 85, 5)), cols = colors,
               axis_title = c("年龄", "年龄别死亡率"))
```



::: {.landscape}

```{epoxy}
## 附表
### {params$year}{params$registry}恶性肿瘤发病情况
```

```{r}
fbsw <- count_canreg(data, cancer_type = "big", age_breaks = c(0, seq(5, 85, 5)), label_tail = "")
agerate <- create_age_rate(fbsw, sex, cancer, decimal = 2) |>
  pivot_wider(id_cols = c(sex, cancer),
              names_from = agegrp,
              values_from = rate)
fbsw <- count_canreg(data, cancer_type = "big")
asr <- create_asr(fbsw, sex, cancer) |>
  select(sex, cancer, cr, prop, asr_cn2000, asr_wld85)
res <- agerate |>
  left_join(asr, by = c("sex", "cancer"))
```


```{r}
#| label: tbl-surfix-inci-total
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤发病情况（合计）")'
  res |> 
    filter(sex == 0) |>
    select(-sex) |> 
    add_labels() |>
    arrange(cancer) |> 
    select(-cancer) |> 
    flextable() |>
  set_header_labels(
    cancer_cn = "部位",
    cr = "粗率\n(1/10万)",
    prop = "构成比\n(%)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)"
    ) |> 
  add_header_row(
    values = c("部位", rep("年龄别发病率", 18),
               "粗率\n(1/10万)", "构成比\n(%)", "中标率\n(1/10万)",
               "世标率\n(1/10万)")) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(i = 1, align = "center", part = "header") |> 
  fontsize(size = 14, part = "header") |> 
  bold(i = 1, part = "header") |> 
  line_spacing(space = 1.3) |>
  fontsize(size = 13) |> 
  theme_report()
```


```{r}
#| label: tbl-surfix-inci-male
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤发病情况（男性）")'
res |> 
  filter(sex == 1) |>
  select(-sex) |> 
  add_labels() |>
  arrange(cancer) |> 
  select(-cancer) |> 
  flextable() |>
  set_header_labels(
    cancer_cn = "部位",
    cr = "粗率\n(1/10万)",
    prop = "构成比\n(%)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)"
    ) |> 
  add_header_row(
    values = c("部位", rep("年龄别发病率", 18),
               "粗率\n(1/10万)", "构成比\n(%)", "中标率\n(1/10万)",
               "世标率\n(1/10万)")) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(i = 1, align = "center", part = "header") |> 
  fontsize(size = 14, part = "header") |> 
  bold(i = 1, part = "header") |> 
  line_spacing(space = 1.3) |>
  fontsize(size = 13) |> 
  theme_report()
```



```{r}
#| label: tbl-surfix-inci-female
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤发病情况（女性）")'
res |> 
  filter(sex == 2) |>
  select(-sex) |> 
  add_labels() |>
  arrange(cancer) |> 
  select(-cancer) |> 
  flextable() |>
  set_header_labels(
    cancer_cn = "部位",
    cr = "粗率\n(1/10万)",
    prop = "构成比\n(%)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)"
    ) |> 
  add_header_row(
    values = c("部位", rep("年龄别发病率", 18),
               "粗率\n(1/10万)", "构成比\n(%)", "中标率\n(1/10万)",
               "世标率\n(1/10万)")) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(i = 1, align = "center", part = "header") |> 
  fontsize(size = 14, part = "header") |> 
  bold(i = 1, part = "header") |> 
  line_spacing(space = 1.3) |>
  fontsize(size = 13) |> 
  theme_report()
```


```{epoxy}
### {params$year}{params$registry}恶性肿瘤死亡情况
```


```{r}
fbsw <- count_canreg(data, cancer_type = "big",
                     age_breaks = c(0, seq(5, 85, 5)), label_tail = "")
agerate <- create_age_rate(fbsw, event="sws", sex, cancer, decimal = 2) |>
  pivot_wider(id_cols = c(sex, cancer),
              names_from = agegrp,
              values_from = rate)
fbsw <- count_canreg(data, cancer_type = "big")
asr <- create_asr(fbsw, event="sws", sex, cancer) |>
  select(sex, cancer, cr, prop, asr_cn2000, asr_wld85)
res <- agerate |>
  left_join(asr, by = c("sex", "cancer"))
```


```{r}
#| label: tbl-surfix-mort-total
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤死亡情况（合计）")'
  res |> 
    filter(sex == 0) |>
    select(-sex) |> 
    add_labels() |>
    arrange(cancer) |> 
    select(-cancer) |> 
    flextable() |>
  set_header_labels(
    cancer_cn = "部位",
    cr = "粗率\n(1/10万)",
    prop = "构成比\n(%)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)"
    ) |> 
  add_header_row(
    values = c("部位", rep("年龄别死亡率", 18),
               "粗率\n(1/10万)", "构成比\n(%)", "中标率\n(1/10万)",
               "世标率\n(1/10万)")) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(i = 1, align = "center", part = "header") |> 
  fontsize(size = 14, part = "header") |> 
  bold(i = 1, part = "header") |> 
  line_spacing(space = 1.3) |>
  fontsize(size = 13) |> 
  theme_report()
```


```{r}
#| label: tbl-surfix-mort-male
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤死亡情况（男性）")'
res |> 
  filter(sex == 1) |>
  select(-sex) |> 
  add_labels() |>
  arrange(cancer) |> 
  select(-cancer) |> 
  flextable() |>
  set_header_labels(
    cancer_cn = "部位",
    cr = "粗率\n(1/10万)",
    prop = "构成比\n(%)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)"
    ) |> 
  add_header_row(
    values = c("部位", rep("年龄别死亡率", 18),
               "粗率\n(1/10万)", "构成比\n(%)", "中标率\n(1/10万)",
               "世标率\n(1/10万)")) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(i = 1, align = "center", part = "header") |> 
  fontsize(size = 14, part = "header") |> 
  bold(i = 1, part = "header") |> 
  line_spacing(space = 1.3) |>
  fontsize(size = 13) |> 
  theme_report()
```


```{r}
#| label: tbl-surfix-mort-female
#| tbl-cap: !expr 'paste0(year, "年", name, "恶性肿瘤死亡情况（女性）")'
res |> 
  filter(sex == 2) |>
  select(-sex) |> 
  add_labels() |>
  arrange(cancer) |> 
  select(-cancer) |> 
  flextable() |>
  set_header_labels(
    cancer_cn = "部位",
    cr = "粗率\n(1/10万)",
    prop = "构成比\n(%)",
    asr_cn2000 = "中标率\n(1/10万)",
    asr_wld85 = "世标率\n(1/10万)"
    ) |> 
  add_header_row(
    values = c("部位", rep("年龄别死亡率", 18),
               "粗率\n(1/10万)", "构成比\n(%)", "中标率\n(1/10万)",
               "世标率\n(1/10万)")) |>
  merge_h(part = "header") |>
  merge_v(part = "header") |>
  align(i = 1, align = "center", part = "header") |> 
  fontsize(size = 14, part = "header") |> 
  bold(i = 1, part = "header") |> 
  line_spacing(space = 1.3) |>
  fontsize(size = 13) |> 
  theme_report()
```

:::
